# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_cEngine', [dirname(__file__)])
        except ImportError:
            import _cEngine
            return _cEngine
        if fp is not None:
            try:
                _mod = imp.load_module('_cEngine', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _cEngine = swig_import_helper()
    del swig_import_helper
else:
    import _cEngine
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class gEngine(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, gEngine, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, gEngine, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _cEngine.new_gEngine(*args)
        try: self.this.append(this)
        except: self.this = this
    def console_new(self, *args): return _cEngine.gEngine_console_new(self, *args)
    def console_remove_console(self, *args): return _cEngine.gEngine_console_remove_console(self, *args)
    def console_get_height_rect(self, *args): return _cEngine.gEngine_console_get_height_rect(self, *args)
    def console_set_default_foreground(self, *args): return _cEngine.gEngine_console_set_default_foreground(self, *args)
    def console_set_default_background(self, *args): return _cEngine.gEngine_console_set_default_background(self, *args)
    def console_print_frame(self, *args): return _cEngine.gEngine_console_print_frame(self, *args)
    def console_print_rect(self, *args): return _cEngine.gEngine_console_print_rect(self, *args)
    def console_blit(self, *args): return _cEngine.gEngine_console_blit(self, *args)
    def console_put_char_ex(self, *args): return _cEngine.gEngine_console_put_char_ex(self, *args)
    def console_set_char(self, *args): return _cEngine.gEngine_console_set_char(self, *args)
    def console_set_alignment(self, *args): return _cEngine.gEngine_console_set_alignment(self, *args)
    def console_print(self, *args): return _cEngine.gEngine_console_print(self, *args)
    def console_flush(self): return _cEngine.gEngine_console_flush(self)
    def console_clear(self, *args): return _cEngine.gEngine_console_clear(self, *args)
    def console_get_char_background(self, *args): return _cEngine.gEngine_console_get_char_background(self, *args)
    def return_color_background(self, *args): return _cEngine.gEngine_return_color_background(self, *args)
    def image_new(self, *args): return _cEngine.gEngine_image_new(self, *args)
    def image_load(self, *args): return _cEngine.gEngine_image_load(self, *args)
    def image_delete(self, *args): return _cEngine.gEngine_image_delete(self, *args)
    def image_clear(self, *args): return _cEngine.gEngine_image_clear(self, *args)
    def image_put_pixel(self, *args): return _cEngine.gEngine_image_put_pixel(self, *args)
    def image_blit_2x(self, *args): return _cEngine.gEngine_image_blit_2x(self, *args)
    def map_init_level(self, *args): return _cEngine.gEngine_map_init_level(self, *args)
    def map_add_tile(self, *args): return _cEngine.gEngine_map_add_tile(self, *args)
    def map_set_properties(self, *args): return _cEngine.gEngine_map_set_properties(self, *args)
    def map_draw(self, *args): return _cEngine.gEngine_map_draw(self, *args)
    def map_is_explored(self, *args): return _cEngine.gEngine_map_is_explored(self, *args)
    __swig_destroy__ = _cEngine.delete_gEngine
    __del__ = lambda self : None;
gEngine_swigregister = _cEngine.gEngine_swigregister
gEngine_swigregister(gEngine)



